name: "DashLord report Action"
description: "Generate a dashlord report"

outputs:
  report-path:
    description: "Path to built website"
    value: ${{ steps.build.outputs.report-path }}

runs:
  using: "composite"
  steps:
    - name: Build
      id: build
      shell: bash
      env:
        SKIP_PREFLIGHT_CHECK: "true"
      run: |
        export DASHLORD_REPO_PATH=${{ github.workspace }};
        echo "DASHLORD_REPO_PATH: $DASHLORD_REPO_PATH"
        cd ${{ github.action_path }}
        yarn
        # this create a report.json to build the website
        # also copies html reports to www/public
        node src > www/src/report.json
        cd www
        yarn
        CI=false yarn build
        touch build/.nojekyll
        echo "::set-output name=report-path::${{ github.action_path }}/www/build"
