name: "DashLord report Action"
description: "Generate a dashlord report"

runs:
  using: "composite"
  steps:
    - name: Build
      shell: bash
      env:
        SKIP_PREFLIGHT_CHECK: "true"
      run: |
        yarn
        # this create a report.json to build the website
        # also copies html reports to www/public
        node src/report > www/src/report.json
        cd www
        yarn
        CI=false yarn build
        touch build/.nojekyll
