name: "DashLord report Action"
description: "Generate a dashlord report"

inputs:
  public-url:
    description: "PUBLIC_URL for the build. see https://create-react-app.dev/docs/using-the-public-folder/#adding-assets-outside-of-the-module-system"
    required: true
    default: /${{ github.repository }}
outputs:
  report-path:
    description: "Path to built website"
    value: ${{ steps.build.outputs.report-path }}

runs:
  using: "composite"
  steps:
    - name: Build
      id: build
      shell: bash
      env:
        SKIP_PREFLIGHT_CHECK: "true"
      run: |
        export REPOSITORY_NAME=/$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')
        export DASHLORD_REPO_PATH=${{ github.workspace }};
        export PUBLIC_URL=$([[ -n "${{ inputs.public-url }}" ]] && echo "${{ inputs.public-url }}" || echo $REPOSITORY_NAME)

        echo "REPOSITORY_NAME: $REPOSITORY_NAME"
        echo "DASHLORD_REPO_PATH: $DASHLORD_REPO_PATH"
        echo "PUBLIC_URL: $PUBLIC_URL"
        
        cd ${{ github.action_path }}
        yarn
        # this create a report.json to build the website
        # also copies html reports to www/public
        node src > www/src/report.json
        cd www
        yarn
        CI=false yarn build
        touch build/.nojekyll
        echo "::set-output name=report-path::${{ github.action_path }}/www/build"
