on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

name: Tests
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          yarn
          yarn test
      - shell: bash
        run: |
          cd www
          yarn
          yarn test
        